### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by drkibitz** [ReSwift/ReSwift-Router#110]
So we do not have to pin to "master" for anything building with Xcode 10

**Comment by DivineDominion** [comment]
Since there's scant active development, the argument can go in either direction: release an arbitrary version and upload a binary for convenience, or don't, because there was virtually no progress.

@mjarvis I don't think it hurts to release 0.6.1 to make life easier for folks using Swift 4.2. Do you have objections?

**Comment by mjarvis** [comment]
I don't object to publishing a new release. However, @Ben-G is the only person with permissions for the cocoapods trunk entry for this (see `pod trunk info ReSwiftRouter`)

**Comment by AdieOlami** [comment]
I get this error in my terminal please

```
   ReSwiftRouter (from `https://github.com/ReSwift/ReSwift-Router.git`) was resolved to 0.6.0, which depends on
      ReSwift (~> 4.0.0)

Specs satisfying the `ReSwift, ReSwift (= 4.1.1), ReSwift (~> 4.0.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by DivineDominion** [comment]
Preparing for this in #117.

**Comment by Ben-G** [comment]
Sorry about that!

Can I add either/both of you folks?

**Comment by DivineDominion** [comment]
Yes, seems you've already done so. Thanks, @Ben-G :)
