### ISSUE TITLE
When debugging sometimes getting, fatal error: [SwiftFlowRouter]:

### ISSUE THREAD

**Issue by avdwerff** [ReSwift/ReSwift-Router#12]
When debugging and hitting breakpoints during active route changes, sometimes I get the following fatal error:

fatal error: [SwiftFlowRouter]: Router is stuck waiting for a completion handler to be called. Ensure that you have called the  completion handler in each Routable element.

**Comment by Ben-G** [comment]
@avdwerff Uh, yes. This is indeed annoying during debugging. I think we should replace it with a warning  that people can use to create conditional breakpoints.

I added the `fatalError` in order to make folks aware that they forgot to call the `completionBlock` when switching to a new route. But I'll look into a better way of accomplishing this.

Thanks for making me aware!

**Comment by MojtabaHs** [comment]
@Ben-G Maybe completionBlock should be optional at all like most of other completion handlers. 🤔
