### ISSUE TITLE
Can't use with ReSwift 6.1.0

### ISSUE THREAD

**Issue by BergQuester** [ReSwift/ReSwift-Router#127]
I'm getting a SPM error with conflicting versions:

![image](https://user-images.githubusercontent.com/1323628/122097991-84817b00-cdcd-11eb-899c-2c419f03f472.png)

**Comment by DivineDominion** [comment]
I think none of us have tested the Router repo with the latest ReSwift versions. The resources for that are lacking since 2019, esp. since none of the core maintainers apparently use the Router lib :) 

That being said, the transition shouldn't be too hard because we didn't change a lot in the past years. But Xcode compatibility and some deprecation notices have to be done. SPM may need some love, too.

@BergQuester if you have the time to try this out, a PR with improvements would be much appreciated!
