### ISSUE TITLE
Router cannot subscribe to Store [ReSwift 0.2.5]

### ISSUE THREAD

**Issue by kouky** [ReSwift/ReSwift-Router#13]
Under ReSwift `0.2.5` the router cannot subscribe to the store during initialization,  [see line 25 in Router.swift](https://github.com/ReSwift/ReSwift-Router/blob/master/ReSwiftRouter/Router.swift#L23).

Cause of the issue was a change in the signature for the store subscribe method, see [ReSwift commit](https://github.com/ReSwift/ReSwift/commit/8230da6f87e2c347e15f71c19277f9e58ecfd18b).

**Comment by Ben-G** [comment]
Sorry for the bad timing in releasing ReSwift core 0.2.5 without updating the Router. I've pushed the necessary changes to master. I still need to issue a new CocoaPods release - ran into an issue so I'll do that tomorrow.

Due to a new feature in ReSwift, the Router will now select the navigation state using the new state selector API (that can be used when subscribing to a store). The `HasNavigationState` protocol will no longer be used. You can checkout the changes in the Readme.

This will allow the router to subscribe to the store again.

Thanks a lot for getting involved :tada:!

**Comment by kouky** [comment]
Not a problem, the new changes look great.
