### ISSUE TITLE
Point of changeRouteSegment method in Routable?

### ISSUE THREAD

**Issue by Bartzy** [ReSwift/ReSwift-Router#71]
Hi,

When should you use `func changeRouteSegment(from: RouteElementIdentifier, to: RouteElementIdentifier, completionHandler: RoutingCompletionHandler) -> Routable`, and how do you implement it at all?

Thanks!

**Comment by Ben-G** [comment]
@Bartzy You would use this method if you need to replace one subroute with another (instead of pushing or popping a route. On iOS this would most likely happen when working with a `UITabBarController` which can switch the presented vc without pushing/popping.

Hope this answers your question! Feel free to re-open if not.

**Comment by Bartzy** [comment]
Thanks for the answer.

How do you implement it though?

**Comment by Ben-G** [comment]
Sorry I missed that part! You can find an example here:
https://github.com/ReSwift/CounterExample-Navigation-TimeTravel/blob/master/ReSwiftCounterExample/AppDelegate.swift#L116-L133

**Comment by Bartzy** [comment]
Thanks!
