### ISSUE TITLE
New Release for ReSwift 4.0 and Deployment Target set to 8.0

### ISSUE THREAD

**Issue by ambientlight** [ReSwift/ReSwift-Router#73]
`ReSwiftRouter` is still maintained right?  

Would be nice to perform the following minor update:
- [ ] new release(0.6.0) so that carthage default uses `ReSwiftRouter` updated for `ReSwift 4.0`
- [ ] change the deployment target or `ReSwiftRouter(master)` to `8.0`

**Comment by Ben-G** [comment]
Hi @ambientlight! Yes this component is still maintained. I'm personally not using it on a project right now, but I believe some other folks are, probably they are not integrating via Carthage.

Will create a PR for deployment target and tag a new release.

**Comment by ambientlight** [comment]
@Ben-G 
Hi @Ben-G! 
Thanks, good to hear, can I ask you why not?)

I personally find this as an amazing tool to have no dependencies between viewControllers.

**Comment by Ben-G** [comment]
Just pushed the 0.6.0 tag and also released via CocoaPods.

>  can I ask you why not?

It happens that I'm currently not working actively on any project that uses ReSwift. At PlanGrid we're using a Flux implementation (since it was easier to add to an existing code base) and currently don't have a full-fledged router (again, harder because of legacy code).

I'm glad you like the library!

**Comment by ambientlight** [comment]
@Ben-G that's sounds sad to me, since I am absolutely in love with how you guys implemented Redux in Swift.
